rasdaemon: Do't process Ampere specific error in the public code
mchehab/rasdaemon pull request #133
Opened 2023-12-14 05:48 UTC by winterddd

Ampere specific error info and error handler need to included in HAVE_AMP_NS_DECODE macro.

2023-12-25 01:23 UTC, axiqia commented
@winterddd `pei_len` can not decode because it is Ampere specific error.

```
Dec 04 11:38:42 xxxx rasdaemon[55843]: <idle>-0     [044]     0.041739: arm_event:            2023-12-04 11:38:41 +0800
Dec 04 11:38:42 xxxx rasdaemon[55843]: affinity: -1
Dec 04 11:38:42 xxxx rasdaemon[55843]: MPIDR: 0x812c0000
Dec 04 11:38:42 xxxx rasdaemon[55843]: MIDR: 0x410fd490
Dec 04 11:38:42 xxxx rasdaemon[55843]: running_state: 1
Dec 04 11:38:42 xxxx rasdaemon[55843]: psci_state: 0<CANT FIND FIELD pei_len>affinity level: 255; MPIDR: 00000000812c0000; MIDR: 00000000410fd490; running state: 1; PSCI state: 0
```
Could you please add details about the problem we met in commit log, so that the maintainer will see why we need this patch.

2024-01-22 06:45 UTC, mchehab requested changes

2024-01-22 06:45 UTC, mchehab commented on ras-arm-handler.c
> +
Coding style nit: please keep all variable declarations at the beginning of the function.

2024-01-22 06:45 UTC, mchehab commented on ras-record.c
> +#endif
Changing the DB format depending if those are declared or not sounds a bad idea, as if one recompiles the code with different options, the DB format will change.

2024-12-19 06:25 UTC, closed without merging